fixed linters errors
richie1988/Microverse-websitepagesproject pull request #7
Opened 2023-07-24 17:46 UTC by richie1988

fixed linters errors

2023-07-24 21:10 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi Team,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-07-24 21:10 UTC, Omar-Muhamad commented on index.js
> +};
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md#:~:text=mobile%20menu%20disappears.-,When%20the%20user%20clicks%20(or%20taps)%20any%20of%20the%20mobile%20menu%20options%2C%20a%20correct%20part%20of%20the%20page%20is%20displayed.,-We%20included%20a), When I click `contact` in mobile menu option it doesn't display the contact form section, please fix that.

2023-07-24 21:10 UTC, Omar-Muhamad commented on mobilepopup.css
> +  }
- [ ] For the line below the mobile menu options, please increase the width of it to match the given design.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://github.com/richie1988/Microverse-websitepagesproject/assets/68796232/25def5e6-65e7-4c26-a79d-f62c78e2a68f) | ![image](https://github.com/richie1988/Microverse-websitepagesproject/assets/68796232/02c96ab3-c7a9-491f-99e0-64b91274688c)  |

2023-07-25 07:39 UTC, KanzaTahreem approved these changes
# Approved 🙌

Hi @richie1988 

Good job implementing the suggested changes 💪 **_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media.tenor.com/xDHCe07zrocAAAAC/congrats-minions.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Styling is looking great, perfect!
-  ✅ Great work using the right GitHub Flow 
-  ✅ Your README looks good, well done!
-  ✅ Linters are working properly, great job! 

## Optional suggestions ❕

_Check out the comments under review_


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 07:39 UTC, KanzaTahreem commented on style.css
>  }
- [OPTIONAL] The cross button is behaving as expected on `375px` However, when I am increasing the width, the button is misplaced ⚠😓 please make sure that it is always placed at the end, could you please fix this? ✨

![image](https://github.com/richie1988/Microverse-websitepagesproject/assets/106119105/3e2ec91a-de6f-49fb-a571-1ec2f2d5664f)

2023-07-25 08:57 UTC, merged